### ISSUE TITLE
Span Issue - Related Posts

### ISSUE THREAD

**Issue by mrkrndvs** [pfefferle/ZenPress#18]
I have returned to ZenPress with my main blog - readwriterespond.com - and found another span issue, this time associated with 'Related Posts'. I am wondering if it relates to the issue associted [Syndicated Posts](https://github.com/pfefferle/ZenPress/issues/10).

![screenshot 2018-03-19 at 11 00 42 pm](https://user-images.githubusercontent.com/13294754/37594539-96c1da66-2bc9-11e8-90f7-735b1667d39a.png)

**Comment by pfefferle** [comment]
is this a JetPack feature?

**Comment by mrkrndvs** [comment]
Yes, I have a workaround. Stop using it :)
