### ISSUE TITLE
Problem with child theme

### ISSUE THREAD

**Issue by jeremycherfas** [pfefferle/ZenPress#2]
Hello, I am trying to make a child theme of ZenPress.

If I leave the structure exactly as here, then WP gives an error that it cannot find the ZenPress parent theme.

If I take out the `\zenpress` folder out and put it under `'themes` then everything seems to work fine, but I am worried about losing the `'sass` folder.

Any advice?

**Comment by pfefferle** [comment]
you've done it correctly... the theme is in the `zenpress` subfolder, the main directory includes some generators and the sass files... but you only need the subfolder...

**Comment by pfefferle** [comment]
I restructured the theme based on your feedback, let me know when your child theme is finished, then I will add a link to the readme!

**Comment by jeremycherfas** [comment]
Thanks for this. My child theme is almost complete, with one problem. I don't like the banner to be quite so large. I tried to reduce the size with this CSS:
````
.page-banner {
	height: 25vh;
	max-height: 25%;
	}
````
This works when I do it in developer mode in Safari, but not when I add it to the child theme `style.css`

I just cannot understand why. If you can offer any suggestions, I would be very grateful.

My site is [www.fornacalia.com](www.fornacalia.com)

Thanks

**Comment by jeremycherfas** [comment]
That's it. Thanks a lot.



I don't think I'll be doing any more tinkering now.





On Sun, 5 Mar 2017, at 03:06 PM, Matthias Pfefferle wrote:

> try



> .site-header .page-banner {  height: 25vh;  max-height: 25%;  }

> instead.



> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].
> 


Links:

  1. https://github.com/pfefferle/ZenPress/issues/2#issuecomment-284230027

**Comment by pfefferle** [comment]
😄 

but be aware, that ZenPress is still work in progress!

**Comment by jeremycherfas** [comment]
I look forward to whatever you will do in future.
