### ISSUE TITLE
header image block is displayed when there is no header image set

### ISSUE THREAD

**Issue by xavierroy** [pfefferle/ZenPress#21]
I added a header image and then removed it. The theme still displays a blank block. 

I think it comes from this declaration: 
`.page-banner{background-color:#5fa7c5;width:100%;position:relative;height:75vh;max-height:75%;min-height:500px}`

If a header image is not set, the height of the banner can be reduced accordingly?

**Comment by pfefferle** [comment]
Reduce it or hide it or a setting to choose between the options?

**Comment by xavierroy** [comment]
Any option would be nice. You can set a default height and also provide an option to reduce it manually? If someone wants to hide it, then can use 0px? :-)

**Comment by pfefferle** [comment]
latest version should fix it! if there is no image, the header is white and way smaller and if you do not want to display the tagline at all, please uncheck "Display Site Title and Tagline" in the "Customizer" -> "Site Identity". Let me know if that works for you.
