### ISSUE TITLE
Aside post format archive missing 

### ISSUE THREAD

**Issue by billbennettnz** [pfefferle/ZenPress#5]
I'm trying to use different post format types on my Zenpress site. The post formats work as expected in the posts, but they do not have archives. So, If you look at the top of this page:

https://billbennett.co.nz/e-mail/

You'll see the the word ASIDE, it links to a what should be an aside archive page: https://billbennett.co.nz/type/aside/

But that defaults back to my home page. 

I notice on this page https://notiz.blog/2016/09/23/indiewordpress-wordcamp-frankfurt/

the VIDEO link does take the user back to a video archive. 

I'm using a Zenpress child theme, but to check the problem is not down to the child theme I tried teh same using the parent theme and the aside link still breaks. 

It's not an obvious plug-in conflict, I disabled them all to test and the link doesn't work as expected.

**Comment by drkokandy** [comment]
I am not encountering this issue on my site;
https://davekokandy.com/type/aside/ seems to be working as expected. I most
recently cloned the theme a few weeks ago.

**Comment by billbennettnz** [comment]
I'll try grabbing the latest files and updating. Will report back.

**Comment by pfefferle** [comment]
Have you tried to regenerate your permalinks? (Go to the permalinks settings site and press save, you do not have to change something)

**Comment by billbennettnz** [comment]
Regenerating permalinks didn't work, nor did installing the latest files. It's late here, I'll look at using the master version of the theme instead of my child version tomorrow. It maybe something I hacked. Actually it's quite likely something I hacked.

**Comment by pfefferle** [comment]
Might be, because I haven‘t changed the core functionality of WordPress here. Perhaps you might want to upload your child theme to github, so that I can have a look?

**Comment by billbennettnz** [comment]
Hmm. The problem seems more fundamental that the theme or plugins. If I deactivate all plugins and switch to the master version of Zenpress I still have the same problem. Likewise if I use one of the default WordPress themes. Sorry to assume it was theme related.

**Comment by pfefferle** [comment]
any news on this?

**Comment by billbennettnz** [comment]
Tracked it down to a problem with the Yoast SEO plug-in. This was hidden when I disabled the plug-in first time because of caching at the host. There’s a thread here, https://wordpress.org/support/topic/problem-with-format-type-archive-pages/

As you can see it’s not resolved, the Yoast team says it’s not reproducible. 

Need to kee- this open for now in case the problem is interaction between Yoast and the theme.

**Comment by pfefferle** [comment]
Ok, thanks for the update.

**Comment by pfefferle** [comment]
I will close this for now, feel free to re-open it if it is still a problem.
