### ISSUE TITLE
except text block in search archive missing left and right margin

### ISSUE THREAD

**Issue by billbennettnz** [pfefferle/ZenPress#7]
On the large screen sizes, above 900px, the entry-content has left and right margins of 100px. However in the search archive page these margins disappear which makes the text look odd. I've read the CSS and it looks like you intended the entry-summary block to line up the same way, but it doesn't. 

I think this is a bug, not a feature, but could be wrong.

**Comment by pfefferle** [comment]
oh, I think you are using an older version... can you try to use the latest version from the GitHub master?
